-- Add added_by column if it doesn't exist
ALTER TABLE vms_visitors 
ADD COLUMN IF NOT EXISTS added_by INT DEFAULT NULL AFTER year_of_graduation,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD CONSTRAINT fk_added_by FOREIGN KEY (added_by) REFERENCES vms_users(id) ON DELETE SET NULL;